-- Update GM Hummer description (from Task 1)
--UPDATE inventory
--SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
--WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update image paths (from Task 1)
--UPDATE inventory
--SET 
  --inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  --inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');




  -- Drop existing tables if they exist
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS classification;
DROP TYPE IF EXISTS account_type;

-- Create custom type
CREATE TYPE account_type AS ENUM ('Client', 'Employee', 'Admin');

-- Create account table
CREATE TABLE account (
    account_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR(20) NOT NULL,
    account_lastname VARCHAR(20) NOT NULL,
    account_email VARCHAR(40) NOT NULL,
    account_password VARCHAR(200) NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'
);

-- Create classification table
CREATE TABLE classification (
    classification_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR(30) NOT NULL
);

-- Create inventory table
CREATE TABLE inventory (
    inv_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inv_make VARCHAR(30) NOT NULL,
    inv_model VARCHAR(30) NOT NULL,
    inv_year CHARACTER(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR(150) NOT NULL,
    inv_thumbnail VARCHAR(150) NOT NULL,
    inv_price NUMERIC(9,0) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color VARCHAR(20) NOT NULL,
    classification_id INTEGER NOT NULL REFERENCES classification(classification_id)
);

-- Insert classification data
INSERT INTO classification (classification_name)
VALUES 
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- Insert inventory data (sample data - you should include your actual data)
INSERT INTO inventory (
    inv_make, inv_model, inv_year, inv_description, inv_image, 
    inv_thumbnail, inv_price, inv_miles, inv_color, classification_id
)
VALUES
('GM', 'Hummer', '2020', 'Do you have 6 kids and like to go offroading? The Hummer gives you a huge interior with an engine to get you out of any muddy or rocky situation.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 10000, 'Yellow', 3),
('Jeep', 'Wrangler', '2019', 'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading whether that be on the rocks or in the mud!', '/images/wrangler.jpg', '/images/wrangler-tn.jpg', 32850, 15000, 'Orange', 3);

-- Add Task 1 queries 4 and 6 at the end
-- 4. Update GM Hummer description
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- 6. Update image paths to include /vehicles
UPDATE inventory
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');